### ISSUE TITLE
get_dumps.chemrxiv does nothing

### ISSUE THREAD

**Issue by pathway** [jannisborn/paperscraper#13]
I got chem_token from figshare.com.

```
from paperscraper.get_dumps import chemrxiv, biorxiv, medrxiv
...
chemrxiv(save_path=chem_save_path, token=chem_token)
```

Running:
```
WARNING:paperscraper.load_dumps: No dump found for chemrxiv. Skipping entry.
WARNING:paperscraper.load_dumps: No dump found for medrxiv. Skipping entry.
0it [00:00, ?it/s]
INFO:paperscraper.get_dumps.utils.chemrxiv.utils:Done, shutting down
```

File `chemrxiv_2021-10-07.jsonl` is created but empty.

Meanwhile med and bio seem to work fine!

**Comment by jannisborn** [comment]
Hi @pathway,
thanks a lot for reporting. To me it seems that the chemrxiv api is down, https://api.figshare.com/v2/articles?institution=259 yields an empty list instead of providing the articles. 
Currently investigating whether others can confirm this but I suspect it has been down for a few weeks already. Will keep you posted but for the time being I assume the problem is not in the scope of this package.

**Comment by jannisborn** [comment]
Bad news @pathway, I found out that chemrxiv is not hosted via the accessible figshare platform anymore. It's available via Engaged now which does not provide any API: https://axial.acs.org/2021/06/10/chemrxiv-open-engage-platform/

Unfortunately, this means that there will not be any support to chemRxiv in the near future :| 
I will refactor the package/ README to reflect this.

**Comment by jannisborn** [comment]
+1 on the local dump thingy - I myself dont have one either anymore.
